- README.md
- rasn-compiler/src/lib.rs
The module definition seems to be missing in the `add_asn_literal` usage examples, resulting in a parsing error.
Not sure if your intention is later to create internally and output a module definition if the user does not provide it, could be a cool feature :)
> docs: Add module wrapper to ASN.1 literal usage examples

- rasn-compiler-tests/tests/parameterization.rs
- rasn-compiler/src/intermediate/utils.rs
This should keep the same behavior of the current snake case conversion, however it now adds only one `_` to a sequence of uppercase letters instead of one `_` per uppercase letter, e.g.,
ASN.1 identifier: `messageID`, from `message_i_d` to `message_id`
ASN.1 module: `ETSI-ITS-CDD`, from `e_t_s_i__i_t_s__c_d_d` to `etsi__its__cdd`
> Snake case conversion enhancement

- rasn-compiler/src/generator/mod.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/lib.rs
Non-Rust bindings generated by custom backends are currently forced to pass through rustfmt. This PR should generalize this.
There is probably a better way to do this (like maybe binding `CompileResult` to a specific `Backend`?), but requires a bit more refactoring.
> General bindings formatting

- rasn-compiler/src/generator/mod.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/mod.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/lib.rs
Makes `Backend` `generate()` return a `String` instead of a `TokenStream` so `Backend` can be used in non-Rust bindings.
Possible fix for #18.
> fix: Backend generate() res TokenStream to String

- rasn-compiler/src/generator/typescript/utils.rs
Currently, every field in compiled TS types is mandatory. This pull request adds the optional tag `?` to fields which are specified as optional in the ASN definitions.
> typescript: add optional fields

- rasn-compiler/src/generator/typescript/mod.rs
Currently, generated TS namespaces are not exported, limiting their usage to TS's global namespaces.
This pull request allows to deal with namespaces that have different contents but share the same name, as the following example describes:
```typescript
import { CAM_PDU_Descriptions as CAM_PDU_Descriptions_V1} from "./types/cam_v1";
import { CAM_PDU_Descriptions as CAM_PDU_Descriptions_V2} from "./types/cam_v2";
type CAM_V1 = CAM_PDU_Descriptions_V1.CAM
type CAM_V2 = CAM_PDU_Descriptions_V2.CAM
```
> typescript: export namespaces

- rasn-compiler/src/lexer/information_object_class.rs
Fixes the missing parsing of the comma in `...,` in an extended Object Set.
Related with #14.
> fix: Take into account comma after ellipsis in parsing extended Object Set

- Cargo.lock
- rasn-compiler-derive/Cargo.toml
- rasn-compiler-tests/tests/simple_types.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/intermediate/mod.rs
- rasn-compiler/src/lexer/enumerated.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/object_identifier.rs
- rasn-compiler/src/lib.rs
- rasn-compiler/src/validator/linking/mod.rs
- rasn-compiler/src/validator/mod.rs
Fixes the parsing of value assignments with a constraint, e.g.: `test-int INTEGER(0..255) = 4`. 
Constraints are ignored as I'm not sure if they are really required for anything.
Relevant standard/sections: X.680 2021 16, 17, 49
Example (at the ~end of file): https://standards.iso.org/iso/14816/ISO14816%20ASN.1%20repository/ISO14816_AVIAEINumberingAndDataStructures.asn
Probably the compiler/derive crate version should also be bumped.
> fix: Parse value assignment with constraint

- rasn-compiler-tests/src/helpers/mod.rs
- rasn-compiler/src/generator/rasn/mod.rs
- rasn-compiler/src/lexer/information_object_class.rs
> Allow the too_many_arguments clippy lint

- rasn-compiler/src/generator/typescript/builder.rs
This PR fixes a problem which generates invalid TS code when an ASN.1 enumerated definition contains comments in its elements. For example, with the following ASN.1 descriptions:
```
CopValue::= ENUMERATED {
noEntry (0),
co2class1 (1), -- below 101 g/km
co2class2 (2), -- 101 to 120 g/km
co2class3 (3), -- 121 to 140 g/km
co2class4 (4), -- 141 to 160 g/km
co2class5 (5), -- 161 to 200 g/km
co2class6 (6), -- 201 to 250 g/km
co2class7 (7), -- above 250 g/km
reservedforUse (8) -- reserved for future CEN and ISO use
} 
```
The output of the compiler incorrectly messes up the variables with the comments.
```js
export enum CopValue {
noEntry = "noEntry",
below 101 g/km
co2class1 = "co2class1",
101 to 120 g / km
co2class2 = "co2class2",
121 to 140 g / km
co2class3 = "co2class3",
141 to 160 g / km …
```
> Typescript: Fix issue on enumerated comment descriptions

- rasn-compiler-tests/tests/simple_types.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/template.rs
- rasn-compiler/src/generator/rasn/utils.rs
Uses `rasn`s `FixedBitString` and `FixedOctetString` for strictly size-constrained `BIT STRING`s and `OCTET STRING`s. Closes #42
> refactor(rasn): use fixed variant for strictly constrained

- rasn-compiler-tests/tests/structured_types.rs
- rasn-compiler/src/intermediate/constraints.rs
- rasn-compiler/src/lexer/constraint.rs
- rasn-compiler/src/lexer/real.rs
- rasn-compiler/src/lexer/sequence.rs
- rasn-compiler/src/lexer/tests/mod.rs
- rasn-compiler/src/validator/linking/constraints.rs
- rasn-compiler/src/validator/linking/mod.rs
Fixes parsing of single subtype constraints
Closes #59
> fix: error parsing single subtype constraint

- rasn-compiler-tests/tests/parse_test.rs
- rasn-compiler/src/validator/linking/mod.rs
Correctly links `DEFAULT` values in `SEQUENCE`s or `SET`s that are nested within a `CHOICE`'s options.
Closes #54
> fix(linker): link defaults in nested choices

- Cargo.lock
- rasn-compiler-tests/Cargo.toml
- rasn-compiler-tests/tests/simple_types.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/utils.rs
Adds GraphicString support the ASN.1 compiler.
Graphic string support was added to rasn in this commit: https://github.com/librasn/rasn/commit/d97c44d4a58076738a2eab345101cc763ccb2178
> feat:enable graphic string

- rasn-compiler/src/error.rs
Addresses #89 for `rasn-compiler` so we can do something like:
```rust
fn main() -> Result<(), Box<dyn Error>> {
Compiler::<RasnBackend, _>::new()
.add_asn_by_path("test.asn")
.set_output_path("./test.rs")
.compile()?;
Ok(())
}
```
> feat(error): implement Error for CompilerError

- rasn-compiler-tests/tests/parameterization.rs
- rasn-compiler/src/generator/rasn/utils.rs
Addresses the case where "Kebab-Case" was converted to "kebab__case". After the change, we get "kebab_case".
issue: #88
> fix(generator): use single underscore in kebab to snake case conversion

- rasn-compiler-tests/tests/structured_types.rs
- rasn-compiler/src/validator/linking/mod.rs
Fixes #95
Stops recursion detection at options and sequence members that are already marked `is_recursive`. Options and members that are marked recursive will be `Box`ed. The `Box` constitutes a recursion breaker, so we do not have to check its children for recursion.
> fix(linker): prevent stack overflow from over-eager recursion marking

- rasn-compiler-tests/tests/structured_types.rs
- rasn-compiler/src/intermediate/encoding_rules/per_visible.rs
- rasn-compiler/src/intermediate/mod.rs
- rasn-compiler/src/lexer/enumerated.rs
- rasn-compiler/src/lexer/error.rs
- rasn-compiler/src/validator/linking/constraints.rs
- rasn-compiler/src/validator/linking/mod.rs
- rasn-compiler/src/validator/mod.rs
Fixes #98
Recursion detection is traveling down the reference graph to detect recursive types. Since this graph is not necessarily acyclic, the compiler needs to keep track of visited nodes in order to detect circular references. A circular reference consists a recursion boundary for the recursion check, because the compiler can safely assume that the recursion present in the circular reference will be detected in a later step.
> fix(linker): build reference graph to stop at circular references in recursion detection

- rasn-compiler-tests/tests/simple_types.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/intermediate/encoding_rules/per_visible.rs
**With this fix this**
```asn1
FQDN ::=
VisibleString(FROM ("a".."z" | "A".."Z" | "0".."9" | ".-"))(SIZE (1..255))
```
**Is compiled correctly as:**
```rust
#[derive(AsnType, Debug, Clone, Decode, Encode, PartialEq, Eq, Hash)]
#[rasn(
delegate,
size("1..=255"),
from(
"\u{2d}",
"\u{2e}",
"\u{30}..=\u{39}",
"\u{41}..=\u{5a}",
"\u{61}..=\u{7a}"
)
)]
pub struct FQDN(pub VisibleString);
```
Without this fix, the "from" is missing and thus the decoding fails.
✅ All tests are passing
> Fixes multiple character subsets parsing

- rasn-compiler/src/bin.rs
- rasn-compiler/src/cli.rs
Prefix all output with blue "info", yellow "warning" or red "error", and do not color the full message. Kind of like how rustc does it.
Report warnings when walking with --directory.
Move the arguments --directory/-d and --module/-m into a required argument group, so that at least one have to be specified. This makes error reporting and --help nicer.
> Some CLI ergonomics

- Cargo.toml
- rasn-compiler-derive/Cargo.toml
- rasn-compiler-tests/Cargo.toml
- rasn-compiler/Cargo.toml
MSRV is determined by using cargo-msrv, which fails on 1.81.0 with:
```
Compatibility Check #7: Rust 1.81.0
[FAIL]   Is incompatible 
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│    Compiling rasn-compiler v0.10.1 (/home/mawa/projects/rasn-compiler/rasn-compiler)                               │
│     Checking rasn v0.26.5                                                                                          │
│ error[E0658]: use of unstable library feature 'iter_repeat_n'                                                      │
│    --> /home/mawa/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rasn-0.26.5/src/oer/enc.rs:516:28           │
│     | …
```
> Set MSRV to 1.82

- rasn-compiler/src/cli.rs
In commit 52e4f7 the `--backend` was accidentally flipped, so that `--backend rasn` would result in "typescript" and vice versa.
Also caused the default to be "typescript".
> fix(cli): Flipped backend selection

- Cargo.lock
- rasn-compiler/Cargo.toml
- rasn-compiler/src/input.rs
- rasn-compiler/src/lexer/bit_string.rs
- rasn-compiler/src/lexer/boolean.rs
- rasn-compiler/src/lexer/character_string.rs
- rasn-compiler/src/lexer/choice.rs
- rasn-compiler/src/lexer/common.rs
- rasn-compiler/src/lexer/constraint.rs
- rasn-compiler/src/lexer/embedded_pdv.rs
- rasn-compiler/src/lexer/enumerated.rs
- rasn-compiler/src/lexer/external.rs
- rasn-compiler/src/lexer/information_object_class.rs
- rasn-compiler/src/lexer/integer.rs
- rasn-compiler/src/lexer/macros.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/module_reference.rs
- rasn-compiler/src/lexer/null.rs
- rasn-compiler/src/lexer/object_identifier.rs
- rasn-compiler/src/lexer/octet_string.rs
- rasn-compiler/src/lexer/parameterization.rs
- rasn-compiler/src/lexer/real.rs
- rasn-compiler/src/lexer/sequence.rs
- rasn-compiler/src/lexer/sequence_of.rs
- rasn-compiler/src/lexer/set.rs
- rasn-compiler/src/lexer/set_of.rs
- rasn-compiler/src/lexer/time.rs
- rasn-compiler/src/lexer/util.rs
Most changes are due to these two:
- Instead of writing `combinator(arg)(input)`, we now write `combinator(arg).parse(input)`.
- InputIter, InputTakeAtPosition, InputLength, InputTake and Slice are now merged in the Input trait.
See [nom changelog](https://github.com/rust-bakery/nom/blob/main/CHANGELOG.md#800-2025-01-25) for details.
> build: Upgrade nom to version 8

- rasn-compiler/src/generator/error.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/intermediate/information_object.rs
- rasn-compiler/src/intermediate/mod.rs
- rasn-compiler/src/intermediate/parameterization.rs
- rasn-compiler/src/lexer/information_object_class.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/tests/mod.rs
- rasn-compiler/src/validator/linking/information_object.rs
- rasn-compiler/src/validator/linking/mod.rs
- rasn-compiler/src/validator/linking/types.rs
- rasn-compiler/src/validator/mod.rs
Information object class have quite different usage/semantics from information object and information object set, so split them into two.
> Split `ToplevelDefinition::Information` into `Object` and `Class`

- rasn-compiler-tests/tests/rasn_kerberos_tests.rs
- rasn-compiler/src/generator/error.rs
- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/mod.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/generator/typescript/builder.rs
- rasn-compiler/src/generator/typescript/mod.rs
- rasn-compiler/src/input.rs
- rasn-compiler/src/intermediate/constraints.rs
- rasn-compiler/src/intermediate/encoding_rules/per_visible.rs
- rasn-compiler/src/intermediate/types.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/object_identifier.rs
- rasn-compiler/src/lexer/set.rs
- rasn-compiler/src/lib.rs
Fix all standard Clippy lints and format with `cargo fmt`.
> Fix Clippy lints

- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/intermediate/constraints.rs
- rasn-compiler/src/intermediate/encoding_rules/per_visible.rs
- rasn-compiler/src/intermediate/mod.rs
- rasn-compiler/src/intermediate/types.rs
- rasn-compiler/src/lexer/bit_string.rs
- rasn-compiler/src/lexer/boolean.rs
- rasn-compiler/src/lexer/character_string.rs
- rasn-compiler/src/lexer/choice.rs
- rasn-compiler/src/lexer/constraint.rs
- rasn-compiler/src/lexer/information_object_class.rs
- rasn-compiler/src/lexer/integer.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/object_identifier.rs
- rasn-compiler/src/lexer/octet_string.rs
- rasn-compiler/src/lexer/real.rs
- rasn-compiler/src/lexer/sequence.rs
- rasn-compiler/src/lexer/sequence_of.rs
- rasn-compiler/src/lexer/set.rs
- rasn-compiler/src/lexer/set_of.rs
- rasn-compiler/src/lexer/tests/mod.rs
- rasn-compiler/src/lexer/time.rs
- rasn-compiler/src/validator/linking/constraints.rs
- rasn-compiler/src/validator/linking/mod.rs
- rasn-compiler/src/validator/mod.rs
Rename types/functions to better follow the specification, and add more comments. Most changes are related to constraints.
> Renames to better follow specification

- rasn-compiler/src/generator/rasn/builder.rs
- rasn-compiler/src/generator/rasn/utils.rs
- rasn-compiler/src/intermediate/mod.rs
- rasn-compiler/src/lexer/choice.rs
- rasn-compiler/src/lexer/constraint.rs
- rasn-compiler/src/lexer/enumerated.rs
- rasn-compiler/src/lexer/information_object_class.rs
- rasn-compiler/src/lexer/macros.rs
- rasn-compiler/src/lexer/mod.rs
- rasn-compiler/src/lexer/sequence.rs
- rasn-compiler/src/lexer/sequence_of.rs
- rasn-compiler/src/lexer/set_of.rs
- rasn-compiler/src/lexer/tests/mod.rs
- rasn-compiler/src/validator/linking/mod.rs
Add support for having type references qualified with module.
That is, partially support the following syntax:
```asn1
MainModule DEFINITIONS ::= BEGIN
IMPORTS
Name FROM ETSI-Common-Types
{ itu-t(0) identified-organization(4) etsi(0) common-parameters(3280) version241(241) }
Name FROM Vendor-Types
{ iso(1) org(3) dod(6) internet(1) private(4) enterprise(1) 99999 42 };
-- Naming collision is resolved by module prefix
ServiceA ::= SEQUENCE {
name ETSI-Common-Types.Name
}
ServiceB ::= SEQUENCE {
name Vendor-Types.Name
}
END
```
That generates:
```rust
#[allow(
non_camel_case_types,
non_snake_case,
non_upper_case_globals,
unused,
clippy::too_many_arguments
)]
pub mod main_module {
extern crate alloc;
use super::etsi_common_types::Name;
use super::vendor_types::Name;
use core::borrow::Borrow; …
```
> Support qualified type references

- rasn-compiler-tests/tests/parse_test.rs
- rasn-compiler/src/bin.rs
- rasn-compiler/src/lib.rs
Allow to configure the compiler with multiple "output modes", and add two new:
- `OutputMode::SingleFile`: Write all bindings to a single file. Previously the only mode.
- `OutputMode::Stdout`: Write all bindings to stdout.
- `OutputMode::NoOutput`: Do not write anything. Useful when only checking.
Marks `Compiler::set_output_path` as deprecated. Use `Compiler::set_output_mode` instead.
This is a small step towards outputting a file per module (issue https://github.com/librasn/compiler/issues/53).
Add two new args:
- `--stdout`: Output generated bindings to stdout.
- `--no-out`: Do not output generated bindings. Useful when checking.
> feat: Output modes
